{{- if eq .Values.type "ReplicaSet" }}
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ .Release.Service }}

spec:
  type: {{ .Values.type | quote }}
  members: {{ .Values.replicaSet.members }}

  # Using a version >= 4.0 will enable SCRAM-SHA-256 authentication
  # setting a version < 4.0 will enable SCRAM-SHA-1/MONGODB-CR authentication
  version: {{ .Values.version }}
  persistent : true
  backup:
    enabled: {{ .Values.backup }}

  opsManager:
    configMapRef:
{{- if .Values.opsManager.configMap }}      
      name: {{ .Values.opsManager.configMap }}
{{- else }}
      name: {{ .Release.Name }}-configmap
{{- end }}
{{- if .Values.opsManager.secretRef }}
  credentials: {{ .Values.opsManager.secretRef }}
{{- else }}
  credentials: {{ .Release.Name }}-credential
{{- end }}

  security:
    authentication:
      enabled: true
      modes: 
        {{- range .Values.security.authentication.modes }}
        - {{ . | quote }} # Valid authentication modes are "SCRAM' and "X509"
        {{- end }}
    {{- if .Values.security.tls.enabled }}
    tls:
      enabled: {{ .Values.security.tls.enabled }}
      ca: {{  .Values.security.tls.caRef }}
    {{- end }}

      # Optional field - ignoreUnknownUsers
      # A value of true means that any users not configured via the Operator or the Ops Manager or Cloud Manager UI
      # will not be altered in any way

      # If you need to manage MongoDB users directly via the mongods, set this value to true
      ignoreUnknownUsers: false # default value false


  additionalMongodConfig:
{{- with .Values.additionalMongodConfig }}
{{- toYaml . | nindent 4 }}
{{- end }}
  
{{- if .Values.externalConnectivity.enable }}
  externalConnectivity:
    {{- with .Values.externalConnectivity.replicaSetHorizons }}
    replicaSetHorizons:
      {{- toYaml . | nindent 6 }}
    {{- end }}    
{{- end }}
{{- if .Values.agent }}
  agent:
{{- toYaml .Values.agent | nindent 4 }}
{{- end }}
  podSpec:
    podTemplate:
      spec:
        terminationGracePeriodSeconds: 10
        containers:
          - name: mongodb-enterprise-database
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}

    persistence:
      {{- toYaml .Values.persistence | nindent 6 }}
{{- end }}
