{{- if eq .Values.type "ShardedCluster" }}
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ .Release.Service }}

spec:
  type: {{ .Values.type | quote }}
  version: {{ .Values.version }}
  persistent : true
  backup:
    enabled: {{ .Values.backup }}   

{{- with .Values.mongos }}
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- with .Values.shardServer }}
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- with .Values.configServer }}
  {{- toYaml . | nindent 2 }}
{{- end }}

  opsManager:
    configMapRef:
{{- if .Values.opsManager.configMap }}      
      name: {{ .Values.opsManager.configMap }}
{{- else }}
      name: {{ .Release.Name }}-configmap
{{- end }}
{{- if .Values.opsManager.secretRef }}
  credentials: {{ .Values.opsManager.secretRef }}
{{- else }}
  credentials: {{ .Release.Name }}-credential
{{- end }}

  security:
    authentication:
      enabled: true
      modes: 
        {{- range .Values.security.authentication.modes }}
        - {{ . | quote }} # Valid authentication modes are "SCRAM' and "X509"
        {{- end }}
    {{- if .Values.security.tls.enabled }}
    tls:
      enabled: {{ .Values.security.tls.enabled }}
      ca: {{  .Values.security.tls.caRef }}
    {{- end }}

      # Optional field - ignoreUnknownUsers
      # A value of true means that any users not configured via the Operator or the Ops Manager or Cloud Manager UI
      # will not be altered in any way

      # If you need to manage MongoDB users directly via the mongods, set this value to true
      ignoreUnknownUsers: false # default value false
  podSpec:
    podTemplate:
      spec:
        terminationGracePeriodSeconds: 10
        topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
          matchLabels:
            foo: bar
          # This container will be added to each pod as a sidecar
        containers:
          - name: mongodb-enterprise-database
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}

    persistence:
      {{- toYaml .Values.persistence | nindent 6 }}
{{- end }}
