{{- range .Values.users }}
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: {{ $.Release.Name }}-{{ .username }}-mongodbuser
  namespace: {{ $.Release.Namespace }}
  annotations:
    "meta.helm.sh/release-name": {{ $.Release.Name }}
    "meta.helm.sh/release-namespace": {{ $.Release.Namespace }}
  labels:
    "helm.sh/chart": {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service }}
spec:
  passwordSecretKeyRef:
    name: {{ $.Release.Name }}-{{ .username }}-secret # the name of the secret that stores this user's password
    key: password # the key in the secret that stores the password
  username: {{ .username }}
  db: {{ .db }}
  mongodbResourceRef:
    name: {{ $.Release.Name }} # The name of the MongoDB resource this user will be added to
  roles:
    {{- toYaml .roles | nindent 6 }}
{{- end }}
