{{- range .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .username }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    "helm.sh/chart": {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service }}
type: Opaque
stringData:
  password: {{ .password | quote}}
{{- end }}
