apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-atlas-operator.name" . }}-metrics-service
  labels:
    {{- include "mongodb-atlas-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    {{- include "mongodb-atlas-operator.selectorLabels" . | nindent 4 }}
