---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-global-admin
  namespace: {{ .Release.Namespace }}
  labels:
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
type: Opaque
data:
    Username: {{ .Values.globalAdmin | b64enc }}
    Password: {{ .Values.globalAdminPassword | b64enc }}
    FirstName: {{ .Values.globalAdminFirstName | b64enc }}
    LastName: {{ .Values.globalAdminLastName  | b64enc }}
