name: "Helm Chart Releaser"
description: "Host a Helm charts repo on GitHub Pages"
inputs:
  version:
    description: "The chart-releaser version to use (default: v1.2.1)"
    required: false
  config:
    description: "The relative path to the chart-releaser config file"
    required: false
  charts_dir:
    description: "The charts directory"
    required: false
    default: charts
  target_folders:
    description: "Specific charts folder inside <charts_dir> for releasing"
    required: false
  charts_repo_url:
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
    required: false
runs:
  using: composite
  steps:
    - run: "$GITHUB_ACTION_PATH/cr.sh"
      shell: bash
