name: "Helm Chart Releaser"
description: "Host a Helm charts repo on GitHub Pages"
inputs:
  version:
    description: "The chart-releaser version to use (default: v1.2.1)"
    required: false
    default: v1.2.1
  config:
    description: "The relative path to the chart-releaser config file"
    required: false
  charts_dir:
    description: "The charts directory"
    required: false
    default: charts
  charts_repo_url:
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
    required: false
  target:
    description: "Specific charts folder inside <charts_dir> for releasing"
    required: false
runs:
  using: composite
  steps:
    - run: |
        chmod +x "$GITHUB_ACTION_PATH/cr.sh"
        export VERSION="${{ inputs.version }}"
        export CONFIG="${{ inputs.config }}"
        export CHART_DIR="${{ inputs.charts_dir }}"

        charts_repo_url="${{ inputs.charts_repo_url }}"
        if [[ -z "$charts_repo_url" ]]; then
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          charts_repo_url="https://$owner.github.io/$repo"
        fi
        export OWNER=$owner
        export REPO=$repo
        export CHART_REPO_URL="$charts_repo_url"

        mapfile -t target< <(echo ${{ inputs.target }})
        "$GITHUB_ACTION_PATH/cr.sh" "${target[@]}"
      shell: bash
